version: "3.9"
services:
  tui:
    container_name: "tui-service"
    build:
      context: ./Tui
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    stdin_open: true
    #tty: true
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  fileio:
    container_name: "fileio-service"
    build:
      context: ./FileIO
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
  root:
    container_name: "root-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    stdin_open: true
    depends_on:
      - tui
      - fileio
    environment:
      DISPLAY: host.docker.internal:0
